# Generated by Django 5.0.8 on 2026-02-22 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0002_chapterreadingprogress"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="chapterreadingprogress",
            new_name="stats_chapt_user_id_52b6a5_idx",
            old_name="stats_chapt_user_id_62809c_idx",
        ),
        migrations.RenameIndex(
            model_name="chapterreadingprogress",
            new_name="stats_chapt_user_id_3c1efd_idx",
            old_name="stats_chapt_user_id_310d74_idx",
        ),
    ]
