# Generated by Django 5.0.8 on 2026-02-23 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0011_alter_story_author"),
        ("stats", "0003_rename_stats_chapt_user_id_62809c_idx_stats_chapt_user_id_52b6a5_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AudioReadingProgress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("progress", models.FloatField(default=0.0)),
                ("position_seconds", models.FloatField(default=0.0)),
                ("duration_seconds", models.FloatField(default=0.0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "audio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audio_reading_progress",
                        to="story.audio",
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audio_reading_progress",
                        to="story.story",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audio_reading_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "audio")},
            },
        ),
        migrations.AddIndex(
            model_name="audioreadingprogress",
            index=models.Index(fields=["user", "story"], name="stats_audio_user_id_3f31d0_idx"),
        ),
        migrations.AddIndex(
            model_name="audioreadingprogress",
            index=models.Index(fields=["user", "audio"], name="stats_audio_user_id_17f3fb_idx"),
        ),
    ]
