# Generated by Django 5.0.8 on 2026-02-23 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0004_audioreadingprogress"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="audioreadingprogress",
            new_name="stats_audio_user_id_b4eca1_idx",
            old_name="stats_audio_user_id_3f31d0_idx",
        ),
        migrations.RenameIndex(
            model_name="audioreadingprogress",
            new_name="stats_audio_user_id_cbe1a4_idx",
            old_name="stats_audio_user_id_17f3fb_idx",
        ),
    ]
