# Generated by Django 5.0.8 on 2026-07-31 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "stats",
            "0005_rename_stats_audio_user_id_3f31d0_idx_stats_audio_user_id_b4eca1_idx_and_more",
        ),
        ("story", "0028_alter_story_language_alter_submission_language"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FileReadingProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[("epub", "EPUB"), ("pdf", "PDF")], max_length=10
                    ),
                ),
                ("progress", models.FloatField(default=0.0)),
                ("position", models.CharField(blank=True, max_length=512, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_reading_progress",
                        to="story.story",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_reading_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "story", "format"],
                        name="stats_filer_user_id_a35978_idx",
                    )
                ],
                "unique_together": {("user", "story", "format")},
            },
        ),
    ]
