# Generated by Django 5.0.8 on 2026-08-21 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0007_analyticsevent"),
        ("story", "0045_blog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="analyticsevent",
            name="blog",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="analytics_events",
                to="story.blog",
            ),
        ),
        migrations.AddIndex(
            model_name="analyticsevent",
            index=models.Index(
                fields=["blog", "event_type"], name="stats_blog_event_idx"
            ),
        ),
    ]
