# Generated by Django 5.0.8 on 2026-08-29 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0009_blogreadingprogress'),
        ('story', '0067_video'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsevent',
            name='event_type',
            field=models.CharField(choices=[('visit', 'Visit'), ('ad_impression', 'Ad impression'), ('reading_session', 'Reading session'), ('listening_session', 'Listening session'), ('watching_session', 'Watching session'), ('completion', 'Completion'), ('download', 'Download')], db_index=True, max_length=32),
        ),
        migrations.CreateModel(
            name='VideoWatchProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.FloatField(default=0.0)),
                ('position_seconds', models.FloatField(default=0.0)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_watch_progress', to='story.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_watch_progress', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_watch_progress', to='story.video')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'story'], name='stats_video_user_id_bf72f7_idx'), models.Index(fields=['user', 'video'], name='stats_video_user_id_a5f8fd_idx')],
                'unique_together': {('user', 'video')},
            },
        ),
    ]
