# Generated by Django 5.0.8 on 2026-08-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0010_alter_analyticsevent_event_type_videowatchprogress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analyticsevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("visit", "Visit"),
                    ("ad_impression", "Ad impression"),
                    ("reading_session", "Reading session"),
                    ("listening_session", "Listening session"),
                    ("watching_session", "Watching session"),
                    ("completion", "Completion"),
                    ("download", "Download"),
                    ("read_along_cue_seek", "Read Along cue seek"),
                    ("read_along_follow_toggle", "Read Along follow toggle"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
    ]
