# Generated by Django 5.0.8 on 2026-09-04 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0011_alter_analyticsevent_event_type'),
        ('story', '0073_story_cached_chapter_reading_minutes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('chapters', 'Chapters'), ('audio', 'Audio'), ('video', 'Video'), ('epub', 'EPUB'), ('pdf', 'PDF'), ('backfill', 'Backfilled from historical progress')], max_length=16)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='story.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
                'indexes': [models.Index(fields=['user', '-completed_at'], name='stats_completion_user_idx'), models.Index(fields=['story'], name='stats_completion_story_idx')],
                'unique_together': {('user', 'story')},
            },
        ),
    ]
