# Generated by Django 5.0.8 on 2026-09-04 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0016_passport_events'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsevent',
            name='event_type',
            field=models.CharField(choices=[('visit', 'Visit'), ('ad_impression', 'Ad impression'), ('reading_session', 'Reading session'), ('listening_session', 'Listening session'), ('watching_session', 'Watching session'), ('completion', 'Completion'), ('download', 'Download'), ('read_along_cue_seek', 'Read Along cue seek'), ('read_along_follow_toggle', 'Read Along follow toggle'), ('quick_read_opened', 'Quick Read opened'), ('quick_read_completed', 'Quick Read completed'), ('quick_read_full_story_clicked', 'Quick Read full story clicked'), ('story_started', 'Story started'), ('story_resumed', 'Story resumed'), ('story_progressed', 'Story progressed'), ('story_completed', 'Story completed'), ('next_story_clicked', 'Next story clicked'), ('country_unlocked', 'Country unlocked'), ('passport_viewed', 'Passport viewed'), ('achievement_unlocked', 'Achievement unlocked')], db_index=True, max_length=32),
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.CharField(max_length=280)),
                ('category', models.CharField(choices=[('reading', 'Reading'), ('countries', 'Countries'), ('genre', 'Genre'), ('streak', 'Streak'), ('quick_read', 'Quick Read')], db_index=True, max_length=20)),
                ('icon', models.CharField(blank=True, max_length=8)),
                ('target_type', models.CharField(choices=[('stories_completed', 'Stories completed'), ('countries_explored', 'Countries explored'), ('genre_completed', 'Stories completed in a genre'), ('streak_days', 'Longest reading streak, in days'), ('quick_reads_completed', 'Quick Reads completed')], db_index=True, max_length=32)),
                ('target_value', models.PositiveIntegerField()),
                ('target_key', models.CharField(blank=True, max_length=140)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('hidden', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'order', 'target_value'],
                'indexes': [models.Index(fields=['active', 'target_type'], name='stats_achievement_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to='stats.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at', 'achievement__order'],
                'indexes': [models.Index(fields=['user', 'completed'], name='stats_userach_user_idx')],
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
