# Generated by Django 5.0.8 on 2026-09-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0019_daily_story_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='category',
            field=models.CharField(choices=[('reading', 'Reading'), ('countries', 'Countries'), ('genre', 'Genre'), ('streak', 'Streak'), ('quick_read', 'Quick Read'), ('journey', 'Journeys')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='target_type',
            field=models.CharField(choices=[('stories_completed', 'Stories completed'), ('countries_explored', 'Countries explored'), ('genre_completed', 'Stories completed in a genre'), ('streak_days', 'Longest reading streak, in days'), ('quick_reads_completed', 'Quick Reads completed'), ('journeys_completed', 'Story Journeys completed')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='analyticsevent',
            name='event_type',
            field=models.CharField(choices=[('visit', 'Visit'), ('ad_impression', 'Ad impression'), ('reading_session', 'Reading session'), ('listening_session', 'Listening session'), ('watching_session', 'Watching session'), ('completion', 'Completion'), ('download', 'Download'), ('read_along_cue_seek', 'Read Along cue seek'), ('read_along_follow_toggle', 'Read Along follow toggle'), ('quick_read_opened', 'Quick Read opened'), ('quick_read_completed', 'Quick Read completed'), ('quick_read_full_story_clicked', 'Quick Read full story clicked'), ('story_started', 'Story started'), ('story_resumed', 'Story resumed'), ('story_progressed', 'Story progressed'), ('story_completed', 'Story completed'), ('next_story_clicked', 'Next story clicked'), ('country_unlocked', 'Country unlocked'), ('passport_viewed', 'Passport viewed'), ('achievement_unlocked', 'Achievement unlocked'), ('journey_started', 'Journey started'), ('journey_completed', 'Journey completed'), ('daily_story_viewed', 'Daily Story viewed'), ('daily_story_started', 'Daily Story started'), ('daily_story_completed', 'Daily Story completed')], db_index=True, max_length=32),
        ),
    ]
