# Generated by Django 5.0.8 on 2026-09-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0021_seed_journey_achievements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsevent',
            name='event_type',
            field=models.CharField(choices=[('visit', 'Visit'), ('ad_impression', 'Ad impression'), ('reading_session', 'Reading session'), ('listening_session', 'Listening session'), ('watching_session', 'Watching session'), ('completion', 'Completion'), ('download', 'Download'), ('read_along_cue_seek', 'Read Along cue seek'), ('read_along_follow_toggle', 'Read Along follow toggle'), ('quick_read_opened', 'Quick Read opened'), ('quick_read_completed', 'Quick Read completed'), ('quick_read_full_story_clicked', 'Quick Read full story clicked'), ('story_started', 'Story started'), ('story_resumed', 'Story resumed'), ('story_progressed', 'Story progressed'), ('story_completed', 'Story completed'), ('next_story_clicked', 'Next story clicked'), ('country_unlocked', 'Country unlocked'), ('passport_viewed', 'Passport viewed'), ('achievement_unlocked', 'Achievement unlocked'), ('journey_started', 'Journey started'), ('journey_completed', 'Journey completed'), ('reaction_added', 'Reaction added'), ('daily_story_viewed', 'Daily Story viewed'), ('daily_story_started', 'Daily Story started'), ('daily_story_completed', 'Daily Story completed')], db_index=True, max_length=32),
        ),
    ]
