# Generated by Django 5.0.8 on 2026-09-08 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0024_quickreadprogress'),
        ('story', '0080_story_show_in_nepali_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='NepalikathaEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(unique=True)),
                ('event_type', models.CharField(choices=[('visit', 'Visit'), ('read', 'Active reading')], max_length=12)),
                ('visitor_id', models.UUIDField(db_index=True)),
                ('session_id', models.UUIDField(db_index=True)),
                ('path', models.CharField(max_length=500)),
                ('story_slug', models.CharField(blank=True, default='', max_length=255)),
                ('duration_seconds', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nepalikatha_events', to='story.story')),
            ],
            options={
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='np_event_type_time_idx')],
            },
        ),
    ]
