# Generated by Django 5.0.8 on 2025-11-23 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("bio", models.TextField(blank=True, null=True)),
                ("image", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("slug", models.SlugField(max_length=256, unique=True)),
                ("about", models.TextField(blank=True, null=True)),
                (
                    "story_type",
                    models.CharField(
                        choices=[
                            ("Short Story", "Short Story"),
                            ("Novel", "Novel"),
                            ("Poetry", "Poetry"),
                        ],
                        default="Short Story",
                        max_length=50,
                    ),
                ),
                ("published_date", models.DateField(blank=True, null=True)),
                ("cover_image", models.URLField(blank=True, null=True)),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="story.author",
                    ),
                ),
                ("genres", models.ManyToManyField(to="story.genre")),
                ("tags", models.ManyToManyField(blank=True, to="story.tag")),
            ],
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("content", models.TextField()),
                ("order", models.PositiveIntegerField()),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="story.story",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("story", "order")},
            },
        ),
    ]
