# Generated by Django 5.0.8 on 2025-11-23 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="story",
            options={"verbose_name": "Story", "verbose_name_plural": "Stories"},
        ),
    ]
