# Generated by Django 5.0.8 on 2025-11-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0002_alter_story_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="story_type",
            field=models.CharField(
                choices=[
                    ("Short Story", "Short Story"),
                    ("Novel", "Novel"),
                    ("Poetry", "Poetry"),
                    ("Non Fiction", "Non Fiction"),
                ],
                default="Short Story",
                max_length=50,
            ),
        ),
    ]
