# Generated by Django 5.0.8 on 2025-11-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0003_alter_story_story_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="slug",
            field=models.SlugField(max_length=256, null=True),
        ),
    ]
