# Generated by Django 5.0.8 on 2025-11-23 19:59

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0004_chapter_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapter",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Text"),
        ),
    ]
