# Generated by Django 5.0.8 on 2025-11-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0005_alter_chapter_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="rating",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="story",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
