# Generated by Django 5.0.8 on 2025-11-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0006_story_rating_story_views"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="genres",
            field=models.ManyToManyField(related_name="stories", to="story.genre"),
        ),
    ]
