# Generated by Django 5.0.8 on 2025-11-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0008_audio"),
    ]

    operations = [
        migrations.AddField(
            model_name="audio",
            name="order",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
