# Generated by Django 5.0.8 on 2025-11-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0009_audio_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="audio",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="audio",
            name="slug",
            field=models.SlugField(max_length=256, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="audio",
            unique_together={("story", "order")},
        ),
    ]
