# Generated by Django 5.0.8 on 2025-11-27 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0010_alter_audio_options_audio_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stories",
                to="story.author",
            ),
        ),
    ]
