# Generated by Django 5.0.8 on 2026-07-29 07:38

import versatileimagefield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0020_story_submitted_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="cover_image_file",
            field=versatileimagefield.fields.VersatileImageField(
                blank=True, null=True, upload_to="story_covers/"
            ),
        ),
    ]
