# Generated by Django 5.0.8 on 2026-07-29 20:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0022_storyview"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="favorite",
            index=models.Index(
                fields=["created_at"], name="story_favor_created_4b0e0a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["created_at"], name="story_revie_created_001add_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["created_at"], name="story_submi_created_4c780a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["reviewed_at"], name="story_submi_reviewe_da5286_idx"
            ),
        ),
    ]
