# Generated by Django 5.0.8 on 2026-07-30 07:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0023_favorite_story_favor_created_4b0e0a_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
