# Generated by Django 5.0.8 on 2026-07-30 09:29
# Manually reordered: add the two new fields first, backfill them from the
# old published_date column, then remove that column — so no existing
# story loses its date during the split.

from django.db import migrations, models


def backfill_dates(apps, schema_editor):
    Story = apps.get_model("story", "Story")
    Story.objects.exclude(published_date__isnull=True).update(
        original_published_date=models.F("published_date"),
        site_published_date=models.F("published_date"),
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0024_story_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="original_published_date",
            field=models.DateField(
                blank=True,
                help_text="When this work was originally published (e.g. for reprints/adaptations of existing works).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="site_published_date",
            field=models.DateField(
                blank=True,
                help_text="When this story went live on WorldStories. Drives recency sorting and the publishing velocity stat.",
                null=True,
            ),
        ),
        migrations.RunPython(backfill_dates, noop_reverse),
        migrations.RemoveField(
            model_name="story",
            name="published_date",
        ),
    ]
