# Generated by Django 5.0.8 on 2026-07-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0025_remove_story_published_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="story_type",
            field=models.CharField(
                choices=[
                    ("Short Story", "Short Story"),
                    ("Novel", "Novel"),
                    ("Novella", "Novella"),
                    ("Poetry", "Poetry"),
                    ("Non Fiction", "Non Fiction"),
                ],
                default="Short Story",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="story_type",
            field=models.CharField(
                choices=[
                    ("Short Story", "Short Story"),
                    ("Novel", "Novel"),
                    ("Novella", "Novella"),
                    ("Poetry", "Poetry"),
                    ("Non Fiction", "Non Fiction"),
                ],
                default="Short Story",
                max_length=50,
            ),
        ),
    ]
