# Generated by Django 5.0.8 on 2026-07-30 19:29
# Manually split: translation_group is added nullable first, then backfilled with
# a UNIQUE uuid4 per existing row via RunPython, then tightened to non-null.
# A plain AddField(default=uuid.uuid4) would evaluate the callable ONCE and give
# every existing story the SAME group id, incorrectly linking them all together.

import uuid
from django.db import migrations, models


def backfill_translation_groups(apps, schema_editor):
    Story = apps.get_model("story", "Story")
    for story_id in Story.objects.values_list("id", flat=True):
        Story.objects.filter(id=story_id).update(translation_group=uuid.uuid4())


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0026_alter_story_story_type_alter_submission_story_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("es", "Spanish"),
                    ("fr", "French"),
                    ("de", "German"),
                    ("pt", "Portuguese"),
                    ("it", "Italian"),
                    ("hi", "Hindi"),
                    ("ja", "Japanese"),
                    ("ko", "Korean"),
                    ("zh", "Chinese"),
                    ("ar", "Arabic"),
                    ("ru", "Russian"),
                ],
                db_index=True,
                default="en",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="translation_group",
            field=models.UUIDField(
                null=True,
                editable=False,
                help_text="Stories sharing this value are treated as translations of the same work.",
            ),
        ),
        migrations.RunPython(backfill_translation_groups, noop_reverse),
        migrations.AlterField(
            model_name="story",
            name="translation_group",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="Stories sharing this value are treated as translations of the same work.",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("es", "Spanish"),
                    ("fr", "French"),
                    ("de", "German"),
                    ("pt", "Portuguese"),
                    ("it", "Italian"),
                    ("hi", "Hindi"),
                    ("ja", "Japanese"),
                    ("ko", "Korean"),
                    ("zh", "Chinese"),
                    ("ar", "Arabic"),
                    ("ru", "Russian"),
                ],
                default="en",
                max_length=10,
            ),
        ),
    ]
