# Generated by Django 5.0.8 on 2026-07-30 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0027_story_language_story_translation_group_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("es", "Spanish"),
                    ("fr", "French"),
                    ("de", "German"),
                    ("pt", "Portuguese"),
                    ("it", "Italian"),
                    ("hi", "Hindi"),
                    ("ne", "Nepali"),
                    ("ja", "Japanese"),
                    ("ko", "Korean"),
                    ("zh", "Chinese"),
                    ("ar", "Arabic"),
                    ("ru", "Russian"),
                ],
                db_index=True,
                default="en",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("es", "Spanish"),
                    ("fr", "French"),
                    ("de", "German"),
                    ("pt", "Portuguese"),
                    ("it", "Italian"),
                    ("hi", "Hindi"),
                    ("ne", "Nepali"),
                    ("ja", "Japanese"),
                    ("ko", "Korean"),
                    ("zh", "Chinese"),
                    ("ar", "Arabic"),
                    ("ru", "Russian"),
                ],
                default="en",
                max_length=10,
            ),
        ),
    ]
