# Generated by Django 5.0.8 on 2026-08-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0029_alter_story_story_type_alter_submission_story_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="audio",
            name="duration_seconds",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
