# Generated by Django 5.0.8 on 2026-08-02 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0030_audio_duration_seconds"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="publish_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional: hide this story from public listings/search until this moment, even while is_published is True. Leave blank to publish immediately (as soon as is_published is True).",
                null=True,
            ),
        ),
    ]
