# Generated by Django 5.0.8 on 2026-08-02 05:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0031_story_publish_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="original_published_day",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Day of month it was originally published, if known. Only meaningful when the month is also set.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(31),
                ],
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="original_published_month",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Month (1-12) it was originally published, if known. Only meaningful when the year is also set.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="original_published_year",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Year the work was originally published, if known (e.g. for reprints/adaptations of existing works).",
                null=True,
            ),
        ),
    ]
