# Generated by Django 5.0.8 on 2026-08-02 06:01

from django.db import migrations


def backfill_parts(apps, schema_editor):
    Story = apps.get_model("story", "Story")
    for story in Story.objects.exclude(original_published_date__isnull=True):
        date = story.original_published_date
        story.original_published_year = date.year
        story.original_published_month = date.month
        story.original_published_day = date.day
        story.save(update_fields=["original_published_year", "original_published_month", "original_published_day"])


def reverse_backfill(apps, schema_editor):
    Story = apps.get_model("story", "Story")
    Story.objects.update(
        original_published_year=None, original_published_month=None, original_published_day=None
    )


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0032_story_original_published_day_and_more"),
    ]

    operations = [
        migrations.RunPython(backfill_parts, reverse_backfill),
    ]
