# Generated by Django 5.0.8 on 2026-08-02 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0033_backfill_original_published_parts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="story",
            name="original_published_date",
        ),
    ]
