# Generated by Django 5.0.8 on 2026-08-09 05:01

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0036_audio_file_size_bytes"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="summary",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Text"
            ),
        ),
    ]
