# Generated by Django 5.0.8 on 2026-08-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0037_story_summary"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="story",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="stories", to="story.category"
            ),
        ),
    ]
