# Generated by Django 5.0.8 on 2026-08-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0038_category_story_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="cached_file_reading_minutes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
