# Generated by Django 5.0.8 on 2026-08-19 07:03

import core.libs.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0039_story_cached_file_reading_minutes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audio",
            name="audio_file",
            field=models.FileField(
                upload_to="story_audios/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp3"]
                    ),
                    core.libs.validators.FileSizeValidator(157286400),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="epub_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="story_files/epubs/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["epub"]
                    ),
                    core.libs.validators.FileSizeValidator(52428800),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="story_files/pdfs/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    ),
                    core.libs.validators.FileSizeValidator(52428800),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="epub_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="submission_epubs/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["epub"]
                    ),
                    core.libs.validators.FileSizeValidator(52428800),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="submission_pdfs/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    ),
                    core.libs.validators.FileSizeValidator(52428800),
                ],
            ),
        ),
    ]
