# Generated by Django 5.0.8 on 2026-08-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0042_epubimportjob"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromptSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "summary_instructions",
                    models.TextField(
                        default="Write a concise, spoiler-free 2-3 paragraph summary of this book for potential readers browsing the site. Focus on premise, tone, and what makes it worth reading — do not reveal the ending.",
                        help_text="Instructions for the 'Generate Summary' admin action. Title, author, and (if selected) chapter content are assembled separately by code — do not template those into this text.",
                    ),
                ),
                (
                    "retrospective_instructions",
                    models.TextField(
                        default="Write a reflective retrospective essay analyzing this book's themes, historical context, reception, and lasting significance, aimed at readers who have already finished it (spoilers are fine).",
                        help_text="Instructions for the 'Generate Retrospective' admin action.",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Generation Prompt Settings",
            },
        ),
        migrations.AddField(
            model_name="story",
            name="retrospective_confidence_note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="story",
            name="retrospective_confident",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="story",
            name="retrospective_error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="story",
            name="retrospective_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("metadata", "Metadata only (title/author)"),
                    ("content", "Full chapter content"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="retrospective_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="summary_confidence_note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="story",
            name="summary_confident",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="story",
            name="summary_error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="story",
            name="summary_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("metadata", "Metadata only (title/author)"),
                    ("content", "Full chapter content"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="summary_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                max_length=16,
                null=True,
            ),
        ),
    ]
