# Generated by Django 5.0.8 on 2026-08-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0043_promptsettings_story_retrospective_confidence_note_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="promptsettings",
            name="retrospective_model",
            field=models.CharField(
                choices=[
                    ("claude-opus-5", "Claude Opus 5 (most capable, most expensive)"),
                    ("claude-sonnet-5", "Claude Sonnet 5 (balanced)"),
                    ("claude-haiku-4-5", "Claude Haiku 4.5 (fastest, cheapest)"),
                ],
                default="claude-sonnet-5",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="promptsettings",
            name="summary_model",
            field=models.CharField(
                choices=[
                    ("claude-opus-5", "Claude Opus 5 (most capable, most expensive)"),
                    ("claude-sonnet-5", "Claude Sonnet 5 (balanced)"),
                    ("claude-haiku-4-5", "Claude Haiku 4.5 (fastest, cheapest)"),
                ],
                default="claude-sonnet-5",
                max_length=32,
            ),
        ),
    ]
