# Generated by Django 5.0.8 on 2026-08-21 04:56

import django.db.models.deletion
import django_ckeditor_5.fields
import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0044_promptsettings_retrospective_model_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=256, unique=True)),
                (
                    "excerpt",
                    models.CharField(
                        blank=True,
                        help_text="Short summary shown on the blog list page and used as the SEO meta description if set.",
                        max_length=300,
                        null=True,
                    ),
                ),
                (
                    "content",
                    django_ckeditor_5.fields.CKEditor5Field(verbose_name="Text"),
                ),
                (
                    "cover_image_file",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True, null=True, upload_to="blog_covers/"
                    ),
                ),
                (
                    "author_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("is_published", models.BooleanField(default=True)),
                (
                    "publish_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional: hide this post from public listings until this moment, even while is_published is True. Leave blank to publish immediately.",
                        null=True,
                    ),
                ),
                (
                    "linked_story",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional — shows a 'Read the full story' link on the published post.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blog_posts",
                        to="story.story",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Post",
                "verbose_name_plural": "Blog Posts",
                "ordering": ["-created_at"],
            },
        ),
    ]
