# Generated by Django 5.0.8 on 2026-08-21 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0045_blog"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="excerpt_confidence_note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blog",
            name="excerpt_confident",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blog",
            name="excerpt_error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blog",
            name="excerpt_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("metadata", "Metadata only (title/author)"),
                    ("content", "Full post content"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="excerpt_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="promptsettings",
            name="excerpt_instructions",
            field=models.TextField(
                default="Write a compelling, SEO-optimized excerpt (roughly 140-160 characters, never more than 300) for this blog post. It doubles as the page's meta description and the teaser shown on the blog list page, so make it concrete and specific — include the post's actual subject/keywords rather than generic phrasing — and write it as a single line of plain text with no markdown, no HTML, and no surrounding quote marks.",
                help_text="Instructions for the 'Generate Excerpt' admin action on blog posts.",
            ),
        ),
        migrations.AddField(
            model_name="promptsettings",
            name="excerpt_model",
            field=models.CharField(
                choices=[
                    ("claude-opus-5", "Claude Opus 5 (most capable, most expensive)"),
                    ("claude-sonnet-5", "Claude Sonnet 5 (balanced)"),
                    ("claude-haiku-4-5", "Claude Haiku 4.5 (fastest, cheapest)"),
                ],
                default="claude-sonnet-5",
                max_length=32,
            ),
        ),
    ]
