# Generated by Django 5.0.8 on 2026-08-23 18:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0047_storyqueue"),
    ]

    operations = [
        migrations.AddField(
            model_name="storyqueue",
            name="about",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="storyqueue",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="queue_items", to="story.category"
            ),
        ),
        migrations.AddField(
            model_name="storyqueue",
            name="cover_image_link",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="storyqueue",
            name="epub_link",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="storyqueue",
            name="genres",
            field=models.ManyToManyField(
                blank=True, related_name="queue_items", to="story.genre"
            ),
        ),
        migrations.AddField(
            model_name="storyqueue",
            name="original_published_day",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(31),
                ],
            ),
        ),
        migrations.AddField(
            model_name="storyqueue",
            name="original_published_month",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
            ),
        ),
        migrations.AddField(
            model_name="storyqueue",
            name="original_published_year",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="storyqueue",
            name="pdf_link",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="storyqueue",
            name="story_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Short Story", "Short Story"),
                    ("Novel", "Novel"),
                    ("Novella", "Novella"),
                    ("Poetry", "Poetry"),
                    ("Non Fiction", "Non Fiction"),
                    ("Religious Text", "Religious Text"),
                    ("Summary", "Summary"),
                ],
                max_length=50,
            ),
        ),
    ]
