# Generated by Django 5.0.8 on 2026-08-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0049_story_country_storyqueue_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storyqueue",
            name="author_name",
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
