# Generated by Django 5.0.8 on 2026-08-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0050_alter_storyqueue_author_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookFetchJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("requested_count", models.PositiveSmallIntegerField()),
                ("created_count", models.PositiveSmallIntegerField(default=0)),
                ("skipped_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="promptsettings",
            name="book_fetch_instructions",
            field=models.TextField(
                default="You are helping curate a public-domain literature library. Suggest real, existing books that are firmly in the public domain (originally published before 1929, or otherwise clearly public domain in the United States) and are not already in the provided list of existing titles. Prefer well-regarded public-domain classics and lesser-known but genuinely worthwhile works, spread across a range of countries, languages of origin, and story types — avoid suggesting only the handful of most obvious famous titles. Write each book's synopsis as a short, SEO-friendly teaser for readers browsing a library site, without spoiling the ending. Only fill in a cover image, epub, or PDF link if you are confident it is a genuine, currently-working, public-domain source (e.g. a Project Gutenberg, Wikimedia Commons, or Internet Archive URL for that exact edition) — leave any of those blank rather than guess or fabricate a URL. Leave any other field blank if you don't have good information for it, rather than guessing.",
                help_text="Instructions for the 'Fetch Book Data' Story Queue admin action.",
            ),
        ),
        migrations.AddField(
            model_name="promptsettings",
            name="book_fetch_model",
            field=models.CharField(
                choices=[
                    ("claude-opus-5", "Claude Opus 5 (most capable, most expensive)"),
                    ("claude-sonnet-5", "Claude Sonnet 5 (balanced)"),
                    ("claude-haiku-4-5", "Claude Haiku 4.5 (fastest, cheapest)"),
                ],
                default="claude-sonnet-5",
                max_length=32,
            ),
        ),
    ]
