# Generated by Django 5.0.8 on 2026-08-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0051_bookfetchjob_promptsettings_book_fetch_instructions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="storyqueue",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("en", "English"),
                    ("es", "Spanish"),
                    ("fr", "French"),
                    ("de", "German"),
                    ("pt", "Portuguese"),
                    ("it", "Italian"),
                    ("hi", "Hindi"),
                    ("ne", "Nepali"),
                    ("ja", "Japanese"),
                    ("ko", "Korean"),
                    ("zh", "Chinese"),
                    ("ar", "Arabic"),
                    ("ru", "Russian"),
                ],
                max_length=10,
            ),
        ),
    ]
