# Generated by Django 5.0.8 on 2026-08-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0052_storyqueue_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="story_type",
            field=models.CharField(
                choices=[
                    ("Short Story", "Short Story"),
                    ("Novel", "Novel"),
                    ("Novella", "Novella"),
                    ("Poetry", "Poetry"),
                    ("Non Fiction", "Non Fiction"),
                    ("Religious Text", "Religious Text"),
                    ("Summary", "Summary"),
                    ("Collection", "Collection"),
                ],
                default="Short Story",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="storyqueue",
            name="story_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Short Story", "Short Story"),
                    ("Novel", "Novel"),
                    ("Novella", "Novella"),
                    ("Poetry", "Poetry"),
                    ("Non Fiction", "Non Fiction"),
                    ("Religious Text", "Religious Text"),
                    ("Summary", "Summary"),
                    ("Collection", "Collection"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="story_type",
            field=models.CharField(
                choices=[
                    ("Short Story", "Short Story"),
                    ("Novel", "Novel"),
                    ("Novella", "Novella"),
                    ("Poetry", "Poetry"),
                    ("Non Fiction", "Non Fiction"),
                    ("Religious Text", "Religious Text"),
                    ("Summary", "Summary"),
                    ("Collection", "Collection"),
                ],
                default="Short Story",
                max_length=50,
            ),
        ),
    ]
