# Generated by Django 5.0.8 on 2026-08-25 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0053_alter_story_story_type_alter_storyqueue_story_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoryType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="story",
            name="story_type",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="storyqueue",
            name="story_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="submission",
            name="story_type",
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name="story",
            name="story_type_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stories",
                to="story.storytype",
            ),
        ),
        migrations.AddField(
            model_name="storyqueue",
            name="story_type_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="queue_items",
                to="story.storytype",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="story_type_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="submissions",
                to="story.storytype",
            ),
        ),
    ]
