# Generated by Django 5.0.8 on 2026-08-25 08:55

from django.db import migrations

STORY_TYPE_NAMES = [
    "Short Story",
    "Novel",
    "Novella",
    "Poetry",
    "Non Fiction",
    "Religious Text",
    "Summary",
    "Collection",
]


def seed_story_types(apps, schema_editor):
    StoryType = apps.get_model("story", "StoryType")
    for name in STORY_TYPE_NAMES:
        StoryType.objects.get_or_create(name=name)


def noop_reverse(apps, schema_editor):
    # Deliberately not deleting the seeded rows on reverse — by the time
    # this could be reversed, real Story/StoryQueue/Submission rows likely
    # reference them (on_delete=PROTECT would block deletion anyway).
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0054_storytype_alter_story_story_type_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_story_types, noop_reverse),
    ]
