# Generated by Django 5.0.8 on 2026-08-25 08:56

from django.db import migrations


def backfill(apps, schema_editor):
    Story = apps.get_model("story", "Story")
    StoryQueue = apps.get_model("story", "StoryQueue")
    Submission = apps.get_model("story", "Submission")
    StoryType = apps.get_model("story", "StoryType")

    story_type_by_name = {st.name: st for st in StoryType.objects.all()}

    for story in Story.objects.all():
        story.story_type_fk = story_type_by_name.get(story.story_type)
        story.save(update_fields=["story_type_fk"])

    for queue_item in StoryQueue.objects.all():
        if queue_item.story_type:
            queue_item.story_type_fk = story_type_by_name.get(queue_item.story_type)
            queue_item.save(update_fields=["story_type_fk"])

    for submission in Submission.objects.all():
        submission.story_type_fk = story_type_by_name.get(submission.story_type)
        submission.save(update_fields=["story_type_fk"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0055_seed_story_types"),
    ]

    operations = [
        migrations.RunPython(backfill, noop_reverse),
    ]
