# Generated by Django 5.0.8 on 2026-08-25 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0056_backfill_story_type_fk"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="story",
            name="story_type",
        ),
        migrations.RemoveField(
            model_name="storyqueue",
            name="story_type",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="story_type",
        ),
        migrations.AlterField(
            model_name="story",
            name="story_type_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stories",
                to="story.storytype",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="story_type_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="submissions",
                to="story.storytype",
            ),
        ),
    ]
