# Generated by Django 5.0.8 on 2026-08-25 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0057_remove_story_story_type_remove_storyqueue_story_type_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="story",
            old_name="story_type_fk",
            new_name="story_type",
        ),
        migrations.RenameField(
            model_name="storyqueue",
            old_name="story_type_fk",
            new_name="story_type",
        ),
        migrations.RenameField(
            model_name="submission",
            old_name="story_type_fk",
            new_name="story_type",
        ),
    ]
