# Generated by Django 5.0.8 on 2026-08-25 09:06

import apps.story.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0058_rename_story_type_fk_story_story_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="story_type",
            field=models.ForeignKey(
                default=apps.story.models.default_story_type_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stories",
                to="story.storytype",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="story_type",
            field=models.ForeignKey(
                default=apps.story.models.default_story_type_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="submissions",
                to="story.storytype",
            ),
        ),
    ]
