# Generated by Django 5.0.8 on 2026-08-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0059_alter_story_story_type_alter_submission_story_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="storyqueue",
            name="content",
            field=models.TextField(blank=True),
        ),
    ]
