# Generated by Django 5.0.8 on 2026-08-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0060_storyqueue_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="storyqueue",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
