# Generated by Django 5.0.8 on 2026-08-29 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0066_blog_linked_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('slug', models.SlugField(max_length=256, null=True)),
                ('youtube_id', models.CharField(max_length=32)),
                ('youtube_url', models.URLField(max_length=512)),
                ('order', models.PositiveIntegerField(default=1)),
                ('duration_seconds', models.FloatField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='story.story')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('story', 'order')},
            },
        ),
    ]
