# Generated by Django 5.0.8 on 2026-09-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0072_story_featured_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='cached_chapter_reading_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
