# Generated by Django 5.0.8 on 2026-09-04 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0074_dailystory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('icon', models.CharField(blank=True, max_length=8)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StoryMood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('admin', 'Set by an administrator'), ('ai', 'Suggested by AI, pending review')], default='admin', max_length=10)),
                ('reviewed', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_moods', to='story.mood')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_moods', to='story.story')),
            ],
        ),
        migrations.AddField(
            model_name='story',
            name='moods',
            field=models.ManyToManyField(blank=True, related_name='stories', through='story.StoryMood', to='story.mood'),
        ),
        migrations.AddIndex(
            model_name='storymood',
            index=models.Index(fields=['mood', 'story'], name='story_moodassign_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='storymood',
            unique_together={('story', 'mood')},
        ),
    ]
