# Generated by Django 5.0.8 on 2026-09-04 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0076_seed_moods'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.URLField(blank=True)),
                ('type', models.CharField(choices=[('curated', 'Curated selection'), ('country', 'Stories from one country'), ('genre', 'Stories of one genre'), ('theme', 'Stories on one theme')], default='curated', max_length=20)),
                ('active', models.BooleanField(db_index=True, default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='StoryJourneyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('required', models.BooleanField(default=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='story.storyjourney')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_items', to='story.story')),
            ],
            options={
                'ordering': ['position', 'id'],
                'unique_together': {('journey', 'story')},
            },
        ),
    ]
