# Generated by Django 5.0.8 on 2026-09-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0079_story_reactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='show_in_nepali_site',
            field=models.BooleanField(db_default=models.Value(False), db_index=True, default=False, help_text='Show this story on the Nepali companion site.'),
        ),
    ]
