# Generated by Django 5.0.8 on 2026-10-07 02:33

import apps.story.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0081_video_aspect_ratio'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('is_default', models.BooleanField(db_index=True, default=False)),
                ('starts_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('title_prefix', models.CharField(blank=True, default='World', max_length=60)),
                ('title_highlight', models.CharField(blank=True, default='Stories', max_length=60)),
                ('title_highlight_from', models.CharField(default='#ed405a', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Use a 6-digit hex colour such as #ed405a.')])),
                ('title_highlight_to', models.CharField(default='#fbbf24', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Use a 6-digit hex colour such as #ed405a.')])),
                ('description', models.TextField(blank=True, max_length=400)),
                ('info_line_1_icon', models.CharField(choices=[('BookOpen', 'BookOpen'), ('BookOpenText', 'BookOpenText'), ('Feather', 'Feather'), ('Globe2', 'Globe2'), ('Headphones', 'Headphones'), ('Languages', 'Languages'), ('Mic2', 'Mic2'), ('Star', 'Star'), ('Sparkles', 'Sparkles'), ('Heart', 'Heart'), ('Users', 'Users'), ('Clock3', 'Clock3'), ('Music', 'Music'), ('Trophy', 'Trophy'), ('Gift', 'Gift'), ('PartyPopper', 'PartyPopper'), ('Crown', 'Crown'), ('Gem', 'Gem'), ('Rocket', 'Rocket'), ('Zap', 'Zap'), ('Sun', 'Sun'), ('Moon', 'Moon'), ('Cloud', 'Cloud'), ('Leaf', 'Leaf'), ('Flower2', 'Flower2'), ('Snowflake', 'Snowflake'), ('TreePine', 'TreePine'), ('Flame', 'Flame'), ('Ghost', 'Ghost'), ('Skull', 'Skull'), ('Candy', 'Candy'), ('Cat', 'Cat'), ('Castle', 'Castle'), ('WandSparkles', 'WandSparkles')], default='BookOpenText', max_length=30)),
                ('info_line_1_text', models.CharField(blank=True, max_length=120)),
                ('info_line_2_icon', models.CharField(choices=[('BookOpen', 'BookOpen'), ('BookOpenText', 'BookOpenText'), ('Feather', 'Feather'), ('Globe2', 'Globe2'), ('Headphones', 'Headphones'), ('Languages', 'Languages'), ('Mic2', 'Mic2'), ('Star', 'Star'), ('Sparkles', 'Sparkles'), ('Heart', 'Heart'), ('Users', 'Users'), ('Clock3', 'Clock3'), ('Music', 'Music'), ('Trophy', 'Trophy'), ('Gift', 'Gift'), ('PartyPopper', 'PartyPopper'), ('Crown', 'Crown'), ('Gem', 'Gem'), ('Rocket', 'Rocket'), ('Zap', 'Zap'), ('Sun', 'Sun'), ('Moon', 'Moon'), ('Cloud', 'Cloud'), ('Leaf', 'Leaf'), ('Flower2', 'Flower2'), ('Snowflake', 'Snowflake'), ('TreePine', 'TreePine'), ('Flame', 'Flame'), ('Ghost', 'Ghost'), ('Skull', 'Skull'), ('Candy', 'Candy'), ('Cat', 'Cat'), ('Castle', 'Castle'), ('WandSparkles', 'WandSparkles')], default='Headphones', max_length=30)),
                ('info_line_2_text', models.CharField(blank=True, max_length=120)),
                ('stat_1_source', models.CharField(choices=[('stories', 'Live: published stories'), ('creators', 'Live: creators'), ('readers', 'Live: readers'), ('custom', 'Custom value')], default='stories', max_length=10)),
                ('stat_1_label', models.CharField(blank=True, default='stories', max_length=40)),
                ('stat_1_value', models.CharField(blank=True, max_length=20)),
                ('stat_2_source', models.CharField(choices=[('stories', 'Live: published stories'), ('creators', 'Live: creators'), ('readers', 'Live: readers'), ('custom', 'Custom value')], default='creators', max_length=10)),
                ('stat_2_label', models.CharField(blank=True, default='creators', max_length=40)),
                ('stat_2_value', models.CharField(blank=True, max_length=20)),
                ('stat_3_source', models.CharField(choices=[('stories', 'Live: published stories'), ('creators', 'Live: creators'), ('readers', 'Live: readers'), ('custom', 'Custom value')], default='readers', max_length=10)),
                ('stat_3_label', models.CharField(blank=True, default='readers', max_length=40)),
                ('stat_3_value', models.CharField(blank=True, max_length=20)),
                ('cta_label', models.CharField(default='Start Reading', max_length=40)),
                ('cta_url', models.CharField(default='/library', max_length=300)),
                ('cta_bg_from', models.CharField(default='#ed405a', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Use a 6-digit hex colour such as #ed405a.')])),
                ('cta_bg_to', models.CharField(default='#f97316', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Use a 6-digit hex colour such as #ed405a.')])),
                ('cta_text_color', models.CharField(default='#ffffff', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Use a 6-digit hex colour such as #ed405a.')])),
                ('background_color', models.CharField(default='#1a212d', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Use a 6-digit hex colour such as #ed405a.')])),
                ('background_image', models.URLField(blank=True)),
                ('accent_color', models.CharField(default='#ed405a', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Use a 6-digit hex colour such as #ed405a.')])),
                ('animation_preset', models.CharField(choices=[('classic', 'Classic — floating reading icons'), ('halloween', 'Halloween — drifting ghosts and flickering flames'), ('winter', 'Winter — falling snow'), ('none', 'None — static background')], default='classic', max_length=20)),
                ('animation_icons', models.JSONField(blank=True, default=apps.story.models.default_hero_icons)),
            ],
            options={
                'ordering': ['-is_default', 'starts_at', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='herotemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='story_herotemplate_single_default'),
        ),
    ]
