# Generated by Django 5.0.8 on 2026-10-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0083_seed_regular_hero_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='herotemplate',
            name='show_info_lines',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='herotemplate',
            name='show_stats',
            field=models.BooleanField(default=True),
        ),
    ]
