# Generated by Django 5.0.8 on 2026-10-07 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0084_herotemplate_row_toggles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herotemplate',
            name='animation_preset',
            field=models.CharField(choices=[('classic', 'Classic — floating reading icons'), ('halloween', 'Halloween — drifting ghosts and flickering flames'), ('winter', 'Winter — falling snow'), ('christmas', 'Christmas — snow, trees, gifts and a twinkling star'), ('none', 'None — static background')], default='classic', max_length=20),
        ),
    ]
