# Generated by Django 5.0.8 on 2026-10-07 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_single_active_site_theme'),
        ('story', '0085_herotemplate_christmas_animation'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='site_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='pages.sitetheme'),
        ),
    ]
