# Generated by Django 5.0.8 on 2026-08-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0040_add_file_upload_validators"),
        ("users", "0004_add_is_active_to_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="preferred_genres",
            field=models.ManyToManyField(
                blank=True, related_name="users_who_prefer", to="story.genre"
            ),
        ),
    ]
