# Generated by Django 5.0.8 on 2026-08-26 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_add_preferred_genres_to_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserLoginLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("country", models.CharField(blank=True, default="", max_length=100)),
                (
                    "country_code",
                    models.CharField(blank=True, default="", max_length=8),
                ),
                ("city", models.CharField(blank=True, default="", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_locations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["country", "created_at"],
                        name="loginloc_country_created_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"], name="loginloc_user_created_idx"
                    ),
                ],
            },
        ),
    ]
