# Generated by Django 5.0.8 on 2026-10-07 03:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('background_color', models.CharField(default='#ffffff', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Use a 6-digit hex colour such as #ed405a.')])),
                ('surface_color', models.CharField(default='#ffffff', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Use a 6-digit hex colour such as #ed405a.')])),
                ('text_color', models.CharField(default='#1d2027', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Use a 6-digit hex colour such as #ed405a.')])),
                ('muted_text_color', models.CharField(default='#6b7280', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Use a 6-digit hex colour such as #ed405a.')])),
                ('heading_color', models.CharField(default='#1d2027', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Use a 6-digit hex colour such as #ed405a.')])),
                ('primary_color', models.CharField(default='#ed405a', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Use a 6-digit hex colour such as #ed405a.')])),
                ('primary_text_color', models.CharField(default='#ffffff', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Use a 6-digit hex colour such as #ed405a.')])),
                ('border_color', models.CharField(default='#e4e4e7', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Use a 6-digit hex colour such as #ed405a.')])),
                ('heading_font', models.CharField(blank=True, choices=[('', 'Site default'), ('Inter', 'Inter'), ('Roboto', 'Roboto'), ('Open Sans', 'Open Sans'), ('Lato', 'Lato'), ('Montserrat', 'Montserrat'), ('Poppins', 'Poppins'), ('Nunito', 'Nunito'), ('Space Grotesk', 'Space Grotesk'), ('DM Sans', 'DM Sans'), ('Raleway', 'Raleway'), ('Merriweather', 'Merriweather'), ('Lora', 'Lora'), ('Playfair Display', 'Playfair Display'), ('Libre Baskerville', 'Libre Baskerville'), ('Crimson Pro', 'Crimson Pro'), ('EB Garamond', 'EB Garamond'), ('Cormorant Garamond', 'Cormorant Garamond'), ('Cinzel', 'Cinzel'), ('Bebas Neue', 'Bebas Neue'), ('Oswald', 'Oswald'), ('Abril Fatface', 'Abril Fatface'), ('Dancing Script', 'Dancing Script'), ('Pacifico', 'Pacifico'), ('Caveat', 'Caveat'), ('Creepster', 'Creepster'), ('Nosifer', 'Nosifer'), ('Mountains of Christmas', 'Mountains of Christmas'), ('Special Elite', 'Special Elite'), ('Press Start 2P', 'Press Start 2P')], max_length=40)),
                ('body_font', models.CharField(blank=True, choices=[('', 'Site default'), ('Inter', 'Inter'), ('Roboto', 'Roboto'), ('Open Sans', 'Open Sans'), ('Lato', 'Lato'), ('Montserrat', 'Montserrat'), ('Poppins', 'Poppins'), ('Nunito', 'Nunito'), ('Space Grotesk', 'Space Grotesk'), ('DM Sans', 'DM Sans'), ('Raleway', 'Raleway'), ('Merriweather', 'Merriweather'), ('Lora', 'Lora'), ('Playfair Display', 'Playfair Display'), ('Libre Baskerville', 'Libre Baskerville'), ('Crimson Pro', 'Crimson Pro'), ('EB Garamond', 'EB Garamond'), ('Cormorant Garamond', 'Cormorant Garamond'), ('Cinzel', 'Cinzel'), ('Bebas Neue', 'Bebas Neue'), ('Oswald', 'Oswald'), ('Abril Fatface', 'Abril Fatface'), ('Dancing Script', 'Dancing Script'), ('Pacifico', 'Pacifico'), ('Caveat', 'Caveat'), ('Creepster', 'Creepster'), ('Nosifer', 'Nosifer'), ('Mountains of Christmas', 'Mountains of Christmas'), ('Special Elite', 'Special Elite'), ('Press Start 2P', 'Press Start 2P')], max_length=40)),
                ('body_font_size', models.PositiveSmallIntegerField(default=18, validators=[django.core.validators.MinValueValidator(14), django.core.validators.MaxValueValidator(24)])),
                ('heading_weight', models.PositiveSmallIntegerField(default=700, validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(900)])),
                ('heading_uppercase', models.BooleanField(default=False)),
                ('radius', models.PositiveSmallIntegerField(default=12, validators=[django.core.validators.MaxValueValidator(40)])),
                ('content_width', models.CharField(choices=[('narrow', 'Narrow (reading width)'), ('normal', 'Normal'), ('wide', 'Wide'), ('full', 'Full width')], default='normal', max_length=10)),
                ('section_spacing', models.CharField(choices=[('compact', 'Compact'), ('normal', 'Normal'), ('relaxed', 'Relaxed')], default='normal', max_length=10)),
                ('background_image', models.URLField(blank=True)),
                ('background_overlay_color', models.CharField(default='#000000', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Use a 6-digit hex colour such as #ed405a.')])),
                ('background_overlay_opacity', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(95)])),
                ('custom_css', models.TextField(blank=True, max_length=20000)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='page',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='pages.pagetheme'),
        ),
    ]
