# Generated by Django 5.0.8 on 2026-10-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_single_active_site_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_publisher_info', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Site settings',
            },
        ),
    ]
