# Generated by Django 5.0.8 on 2026-09-07 08:36

import apps.social_media_analytics.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=128, unique=True)),
                ('platform', models.CharField(choices=[('facebook', 'Facebook Page'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('youtube', 'YouTube')], max_length=20)),
                ('code_verifier', models.CharField(blank=True, default='', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_oauth_states', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook Page'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('youtube', 'YouTube')], max_length=20)),
                ('external_account_id', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('access_token', apps.social_media_analytics.fields.EncryptedTextField(blank=True, default='')),
                ('refresh_token', apps.social_media_analytics.fields.EncryptedTextField(blank=True, default='')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_status', models.CharField(blank=True, default='', max_length=20)),
                ('last_sync_error', models.TextField(blank=True, default='')),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_platform_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'platform connection',
                'verbose_name_plural': 'platform connections',
            },
        ),
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform_content_id', models.CharField(max_length=255)),
                ('content_type', models.CharField(choices=[('post', 'Post'), ('reel', 'Reel'), ('video', 'Video'), ('story', 'Story')], default='post', max_length=20)),
                ('caption_or_title', models.TextField(blank=True, default='')),
                ('permalink', models.URLField(blank=True, default='', max_length=1000)),
                ('thumbnail_url', models.URLField(blank=True, default='', max_length=1000)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('platform_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_items', to='social_media_analytics.platformconnection')),
            ],
            options={
                'ordering': ['-published_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AccountSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('follower_count', models.BigIntegerField(blank=True, null=True)),
                ('total_views_lifetime', models.BigIntegerField(blank=True, null=True)),
                ('platform_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_snapshots', to='social_media_analytics.platformconnection')),
            ],
            options={
                'ordering': ['-captured_at'],
                'get_latest_by': 'captured_at',
            },
        ),
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook Page'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('youtube', 'YouTube')], max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], max_length=20)),
                ('items_synced', models.IntegerField(default=0)),
                ('snapshots_written', models.IntegerField(default=0)),
                ('message', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['platform', '-started_at'], name='social_medi_platfor_2cb8e0_idx')],
            },
        ),
        migrations.CreateModel(
            name='MetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('views', models.BigIntegerField(blank=True, null=True)),
                ('likes', models.BigIntegerField(blank=True, null=True)),
                ('comments', models.BigIntegerField(blank=True, null=True)),
                ('shares', models.BigIntegerField(blank=True, null=True)),
                ('saves', models.BigIntegerField(blank=True, null=True)),
                ('impressions', models.BigIntegerField(blank=True, null=True)),
                ('reach', models.BigIntegerField(blank=True, null=True)),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='social_media_analytics.contentitem')),
            ],
            options={
                'ordering': ['-captured_at'],
                'get_latest_by': 'captured_at',
                'indexes': [models.Index(fields=['content_item', '-captured_at'], name='social_medi_content_4fd3f9_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='platformconnection',
            index=models.Index(fields=['user', 'platform'], name='social_medi_user_id_ef2887_idx'),
        ),
        migrations.AddConstraint(
            model_name='platformconnection',
            constraint=models.UniqueConstraint(fields=('user', 'platform', 'external_account_id'), name='uniq_social_connection_per_account'),
        ),
        migrations.AddIndex(
            model_name='contentitem',
            index=models.Index(fields=['platform_connection', '-published_at'], name='social_medi_platfor_9f107d_idx'),
        ),
        migrations.AddIndex(
            model_name='contentitem',
            index=models.Index(fields=['-published_at'], name='social_medi_publish_bf509c_idx'),
        ),
        migrations.AddConstraint(
            model_name='contentitem',
            constraint=models.UniqueConstraint(fields=('platform_connection', 'platform_content_id'), name='uniq_social_content_per_connection'),
        ),
        migrations.AddIndex(
            model_name='accountsnapshot',
            index=models.Index(fields=['platform_connection', '-captured_at'], name='social_medi_platfor_647501_idx'),
        ),
    ]
